/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as R500RouteImport } from './routes/500'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedKeysIndexRouteImport } from './routes/_authenticated/keys/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedUsageLogsIndexRouteImport } from './routes/_authenticated/usage-logs/index'
import { Route as AuthenticatedOpsChannelsIndexRouteImport } from './routes/_authenticated/ops/channels/index'
import { Route as AuthenticatedOpsOverviewIndexRouteImport } from './routes/_authenticated/ops/overview/index'
import { Route as AuthenticatedOpsRulesIndexRouteImport } from './routes/_authenticated/ops/rules/index'
import { Route as AuthenticatedOrgBillingIndexRouteImport } from './routes/_authenticated/org/billing/index'
import { Route as AuthenticatedOrgDepartmentsIndexRouteImport } from './routes/_authenticated/org/departments/index'
import { Route as AuthenticatedOrgKeysBatchIndexRouteImport } from './routes/_authenticated/org/keys-batch/index'
import { Route as AuthenticatedOrgMembersIndexRouteImport } from './routes/_authenticated/org/members/index'
import { Route as AuthenticatedOrgPolicyIndexRouteImport } from './routes/_authenticated/org/policy/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeysIndexRoute = AuthenticatedKeysIndexRouteImport.update({
  id: '/keys/',
  path: '/keys/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsageLogsIndexRoute =
  AuthenticatedUsageLogsIndexRouteImport.update({
    id: '/usage-logs/',
    path: '/usage-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsChannelsIndexRoute =
  AuthenticatedOpsChannelsIndexRouteImport.update({
    id: '/ops/channels/',
    path: '/ops/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsOverviewIndexRoute =
  AuthenticatedOpsOverviewIndexRouteImport.update({
    id: '/ops/overview/',
    path: '/ops/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpsRulesIndexRoute =
  AuthenticatedOpsRulesIndexRouteImport.update({
    id: '/ops/rules/',
    path: '/ops/rules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgBillingIndexRoute =
  AuthenticatedOrgBillingIndexRouteImport.update({
    id: '/org/billing/',
    path: '/org/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgDepartmentsIndexRoute =
  AuthenticatedOrgDepartmentsIndexRouteImport.update({
    id: '/org/departments/',
    path: '/org/departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgKeysBatchIndexRoute =
  AuthenticatedOrgKeysBatchIndexRouteImport.update({
    id: '/org/keys-batch/',
    path: '/org/keys-batch/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgMembersIndexRoute =
  AuthenticatedOrgMembersIndexRouteImport.update({
    id: '/org/members/',
    path: '/org/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrgPolicyIndexRoute =
  AuthenticatedOrgPolicyIndexRouteImport.update({
    id: '/org/policy/',
    path: '/org/policy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/keys/': typeof AuthenticatedKeysIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/usage-logs/': typeof AuthenticatedUsageLogsIndexRoute
  '/ops/channels/': typeof AuthenticatedOpsChannelsIndexRoute
  '/ops/overview/': typeof AuthenticatedOpsOverviewIndexRoute
  '/ops/rules/': typeof AuthenticatedOpsRulesIndexRoute
  '/org/billing/': typeof AuthenticatedOrgBillingIndexRoute
  '/org/departments/': typeof AuthenticatedOrgDepartmentsIndexRoute
  '/org/keys-batch/': typeof AuthenticatedOrgKeysBatchIndexRoute
  '/org/members/': typeof AuthenticatedOrgMembersIndexRoute
  '/org/policy/': typeof AuthenticatedOrgPolicyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/keys': typeof AuthenticatedKeysIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/usage-logs': typeof AuthenticatedUsageLogsIndexRoute
  '/ops/channels': typeof AuthenticatedOpsChannelsIndexRoute
  '/ops/overview': typeof AuthenticatedOpsOverviewIndexRoute
  '/ops/rules': typeof AuthenticatedOpsRulesIndexRoute
  '/org/billing': typeof AuthenticatedOrgBillingIndexRoute
  '/org/departments': typeof AuthenticatedOrgDepartmentsIndexRoute
  '/org/keys-batch': typeof AuthenticatedOrgKeysBatchIndexRoute
  '/org/members': typeof AuthenticatedOrgMembersIndexRoute
  '/org/policy': typeof AuthenticatedOrgPolicyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/keys/': typeof AuthenticatedKeysIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/usage-logs/': typeof AuthenticatedUsageLogsIndexRoute
  '/_authenticated/ops/channels/': typeof AuthenticatedOpsChannelsIndexRoute
  '/_authenticated/ops/overview/': typeof AuthenticatedOpsOverviewIndexRoute
  '/_authenticated/ops/rules/': typeof AuthenticatedOpsRulesIndexRoute
  '/_authenticated/org/billing/': typeof AuthenticatedOrgBillingIndexRoute
  '/_authenticated/org/departments/': typeof AuthenticatedOrgDepartmentsIndexRoute
  '/_authenticated/org/keys-batch/': typeof AuthenticatedOrgKeysBatchIndexRoute
  '/_authenticated/org/members/': typeof AuthenticatedOrgMembersIndexRoute
  '/_authenticated/org/policy/': typeof AuthenticatedOrgPolicyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/500'
    | '/dashboard/'
    | '/keys/'
    | '/models/'
    | '/usage-logs/'
    | '/ops/channels/'
    | '/ops/overview/'
    | '/ops/rules/'
    | '/org/billing/'
    | '/org/departments/'
    | '/org/keys-batch/'
    | '/org/members/'
    | '/org/policy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/500'
    | '/dashboard'
    | '/keys'
    | '/models'
    | '/usage-logs'
    | '/ops/channels'
    | '/ops/overview'
    | '/ops/rules'
    | '/org/billing'
    | '/org/departments'
    | '/org/keys-batch'
    | '/org/members'
    | '/org/policy'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/404'
    | '/500'
    | '/_authenticated/dashboard/'
    | '/_authenticated/keys/'
    | '/_authenticated/models/'
    | '/_authenticated/usage-logs/'
    | '/_authenticated/ops/channels/'
    | '/_authenticated/ops/overview/'
    | '/_authenticated/ops/rules/'
    | '/_authenticated/org/billing/'
    | '/_authenticated/org/departments/'
    | '/_authenticated/org/keys-batch/'
    | '/_authenticated/org/members/'
    | '/_authenticated/org/policy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R404Route: typeof R404Route
  R500Route: typeof R500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keys/': {
      id: '/_authenticated/keys/'
      path: '/keys'
      fullPath: '/keys/'
      preLoaderRoute: typeof AuthenticatedKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usage-logs/': {
      id: '/_authenticated/usage-logs/'
      path: '/usage-logs'
      fullPath: '/usage-logs/'
      preLoaderRoute: typeof AuthenticatedUsageLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/channels/': {
      id: '/_authenticated/ops/channels/'
      path: '/ops/channels'
      fullPath: '/ops/channels/'
      preLoaderRoute: typeof AuthenticatedOpsChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/overview/': {
      id: '/_authenticated/ops/overview/'
      path: '/ops/overview'
      fullPath: '/ops/overview/'
      preLoaderRoute: typeof AuthenticatedOpsOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/rules/': {
      id: '/_authenticated/ops/rules/'
      path: '/ops/rules'
      fullPath: '/ops/rules/'
      preLoaderRoute: typeof AuthenticatedOpsRulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/billing/': {
      id: '/_authenticated/org/billing/'
      path: '/org/billing'
      fullPath: '/org/billing/'
      preLoaderRoute: typeof AuthenticatedOrgBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/departments/': {
      id: '/_authenticated/org/departments/'
      path: '/org/departments'
      fullPath: '/org/departments/'
      preLoaderRoute: typeof AuthenticatedOrgDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/keys-batch/': {
      id: '/_authenticated/org/keys-batch/'
      path: '/org/keys-batch'
      fullPath: '/org/keys-batch/'
      preLoaderRoute: typeof AuthenticatedOrgKeysBatchIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/members/': {
      id: '/_authenticated/org/members/'
      path: '/org/members'
      fullPath: '/org/members/'
      preLoaderRoute: typeof AuthenticatedOrgMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/org/policy/': {
      id: '/_authenticated/org/policy/'
      path: '/org/policy'
      fullPath: '/org/policy/'
      preLoaderRoute: typeof AuthenticatedOrgPolicyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedKeysIndexRoute: typeof AuthenticatedKeysIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedUsageLogsIndexRoute: typeof AuthenticatedUsageLogsIndexRoute
  AuthenticatedOpsChannelsIndexRoute: typeof AuthenticatedOpsChannelsIndexRoute
  AuthenticatedOpsOverviewIndexRoute: typeof AuthenticatedOpsOverviewIndexRoute
  AuthenticatedOpsRulesIndexRoute: typeof AuthenticatedOpsRulesIndexRoute
  AuthenticatedOrgBillingIndexRoute: typeof AuthenticatedOrgBillingIndexRoute
  AuthenticatedOrgDepartmentsIndexRoute: typeof AuthenticatedOrgDepartmentsIndexRoute
  AuthenticatedOrgKeysBatchIndexRoute: typeof AuthenticatedOrgKeysBatchIndexRoute
  AuthenticatedOrgMembersIndexRoute: typeof AuthenticatedOrgMembersIndexRoute
  AuthenticatedOrgPolicyIndexRoute: typeof AuthenticatedOrgPolicyIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedKeysIndexRoute: AuthenticatedKeysIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedUsageLogsIndexRoute: AuthenticatedUsageLogsIndexRoute,
  AuthenticatedOpsChannelsIndexRoute: AuthenticatedOpsChannelsIndexRoute,
  AuthenticatedOpsOverviewIndexRoute: AuthenticatedOpsOverviewIndexRoute,
  AuthenticatedOpsRulesIndexRoute: AuthenticatedOpsRulesIndexRoute,
  AuthenticatedOrgBillingIndexRoute: AuthenticatedOrgBillingIndexRoute,
  AuthenticatedOrgDepartmentsIndexRoute: AuthenticatedOrgDepartmentsIndexRoute,
  AuthenticatedOrgKeysBatchIndexRoute: AuthenticatedOrgKeysBatchIndexRoute,
  AuthenticatedOrgMembersIndexRoute: AuthenticatedOrgMembersIndexRoute,
  AuthenticatedOrgPolicyIndexRoute: AuthenticatedOrgPolicyIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R404Route: R404Route,
  R500Route: R500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
